name: Deploy Seguro para GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar o código do repositório
        uses: actions/checkout@v4

      # Correção: Passamos a secret para uma variável de ambiente (env) para o sed não bugar
      - name: Injetar URL Secreta no index.html
        env:
          MINHA_API_URL: ${{ secrets.URL_MINHA_API }}
        run: |
          sed -i "s|REPLACE_WITH_API_URL|$MINHA_API_URL|g" index.html

      - name: Enviar para o GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
          branch: gh-pages
